### ISSUE TITLE
 Error: EACCES: permission denied, stat '/app/.meteor/local/dev_bundle'

### ISSUE THREAD

**Issue by lizzymendivil** [staeke/meteor-alpine#1]
Hello, I am trying to use your image as my image base. What am I missing? Thanks.

**Dockerfile**

`FROM staeke/meteor-alpine:1.8.0.2

USER meteor

WORKDIR /app

CMD ["bash", "entrypoint.sh"]`

**entrypoint.sh**

`#!/bin/bash

if [ -e packages/nickel-core ]; then
    echo "Nickel Meteor packages found."
else
    echo "Obtaining Nickel Meteor packages."
    wget http://172.21.19.33:8090/nickel/0.1.0/packages.tar.gz
    tar -xvf packages.tar.gz --skip-old-files
    rm packages.tar.gz
fi

echo "Installing Nickel and other dependencies."
meteor npm set registry http://172.21.19.33:4873
meteor npm install
meteor add nickel:core
meteor add nickel:admin

meteor npm run debug`

**ERROR** 

`user@ubuntu:~/JDS-CLOUD-LIZZY/cloud$ sudo docker-compose up jds-cloud
Creating network "cloud_app-network" with driver "bridge"
Creating cloud_jds-cloud_1 ... done
Attaching to cloud_jds-cloud_1
jds-cloud_1  | Nickel Meteor packages found.
jds-cloud_1  | Installing Nickel and other dependencies.
jds-cloud_1  | /home/meteor/.meteor/packages/meteor-tool/.1.8.0_2.1om3lwx.sy8++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/cli/dev-bundle.js:119
jds-cloud_1  |       throw e;
jds-cloud_1  |       ^
jds-cloud_1  |
jds-cloud_1  | Error: EACCES: permission denied, stat '/app/.meteor/local/dev_bundle'
jds-cloud_1  |     at Object.fs.statSync (fs.js:948:11)
jds-cloud_1  |     at statOrNull (/home/meteor/.meteor/packages/meteor-tool/.1.8.0_2.1om3lwx.sy8++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/cli/dev-bundle.js:116:19)
jds-cloud_1  |     at getDevBundleDir (/home/meteor/.meteor/packages/meteor-tool/.1.8.0_2.1om3lwx.sy8++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/cli/dev-bundle.js:36:23)
jds-cloud_1  |     at Object.<anonymous> (/home/meteor/.meteor/packages/meteor-tool/.1.8.0_2.1om3lwx.sy8++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/cli/dev-bundle.js:184:18)
jds-cloud_1  |     at Module._compile (module.js:652:30)
jds-cloud_1  |     at Object.Module._extensions..js (module.js:663:10)
jds-cloud_1  |     at Module.load (module.js:565:32)
jds-cloud_1  |     at tryModuleLoad (module.js:505:12)
jds-cloud_1  |     at Function.Module._load (module.js:497:3)
jds-cloud_1  |     at Module.require (module.js:596:17)
jds-cloud_1  | /home/meteor/.meteor/packages/meteor-tool/.1.8.0_2.1om3lwx.sy8++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/tools/cli/dev-bundle.js:119
jds-cloud_1  |       throw e;
jds-cloud_1  |       ^
`

**Comment by staeke** [comment]
Hello @lizzymendivil 

I believe the problem is that `/app` is owned by `root` but you're running as the `meteor` user. When running `WORKDIR /app`, that directory is actually created  You first need to decide if you want to run as `root` or `meteor`. If you want to run as `root`, just skip the `USER meteor` line. However, otherwise I'd put

```
RUN chown meteor /app
```

as a command, before the `USER meteor` statement (but after `WORKDIR /app`).

Also, please note that if you're sharing an existing directory with the host for `/app`, then the container inherits that. That can be tricky to manage.

**Comment by lizzymendivil** [comment]
Thanks staeke, now my Dockerfile looks like this but I keep getting the same error :S
Second question, can I use meteor 1.8.1?

> FROM staeke/meteor-alpine:1.8.0.2
> 
> WORKDIR /app
> 
> RUN chown meteor /app
> 
> USER meteor
> 
> CMD ["bash", "entrypoint.sh"]
>

**Comment by staeke** [comment]
I haven’t released meteor 1.8.1. Can do thtat tonight (US west cost). Regarding the rest - can you give me the command you run your container with? More specifically, are you mounting ”/app”?

**Comment by lizzymendivil** [comment]
I am using these commands:

> sudo docker-compose build jds-cloud
> sudo docker-compose up jds-cloud (Here I am getting the error)

**docker-compose.yml**

> version: '3'
> volumes:
>   mongodata:
> 
> services:
> 
>   jds-cloud:
>     build:
>       context: jds-cloud
>       dockerfile: Dockerfile
>     volumes:
>       - ./jds-cloud:/app
>     networks:
>       - app-network
>     ports:
>       - ${CLIENT_PORT}:3000
>       - ${SERVER_PORT}:3002
> 
> networks:
>   app-network:
>     driver: bridge
>

**Comment by staeke** [comment]
Gotcha. And the files in jds-cloud - what permissions do they have? I’d have to test but I believe the permissons from the actual directory would trickle down too. Thus you might wanna try to just start as root one time. I.e. skip the USER command and just CMD bash. Then run (as root)

```
chown -R :1001 /app
```

Then try again as you did

**Comment by staeke** [comment]
I have now published an image for Meteor 1.8.1 (and 1.8.2)

**Comment by staeke** [comment]
So I just created a new meteor app on my Mac with 

```bash
meteor create --minimal  ./my-app
```

With the `Dockerfile`

```Dockerfile
FROM staeke/meteor-alpine:1.8.2
USER meteor
WORKDIR /app
CMD ["bash", "-c", "meteor npm install && meteor run"]
```

...I then ran:

```bash
docker build . -t met182
docker run -p3000:3000 -it \
    -v $(pwd)/my-app:/app \
    -v $(pwd)/linux_node_modules:/app/node_modules \
    met182
```

with no problems.

So that leads me to believe that you have a permission problem. Your stack trace seems to point to `/app/.meteor/local/dev_bundle`. If I were you I'd run something like

```bash
docker run -p3000:3000 -it \
    -v $(pwd)/jds-cloud:/app \
    staeke/meteor-alpine
bash-5.0$  chmod -R :1001 /app
```

**Comment by v4ld3rr4m4** [comment]
So this issue continues open...  Nobody confirm that process is ok?

I have the same problem about dev_bundle

**Comment by v4ld3rr4m4** [comment]
> Thanks staeke, now my Dockerfile looks like this but I keep getting the same error :S Second question, can I use meteor 1.8.1?
> 
> > FROM staeke/meteor-alpine:1.8.0.2
> > WORKDIR /app
> > RUN chown meteor /app
> > USER meteor
> > CMD ["bash", "entrypoint.sh"]

Could You resolve @lizzymendivil ?
